
export const places = [
  {
    id: 'rajabhakti-park',
    name: 'Rajabhakti Park',
    tag: 'History',
    preview: 'A majestic park honoring seven great Thai kings with towering bronze statues set against the Hua Hin hills.',
    description: 'Rajabhakti Park is a monumental tribute to Thailand\'s revered monarchs. Located at the foot of Khao Noi hill in Hua Hin, this expansive park features seven massive bronze statues of Thai kings from different dynasties, each standing over 12 meters tall. The park was built to honor the rulers who significantly contributed to Thailand\'s independence and development. Surrounded by beautifully manicured gardens and reflective pools, it offers visitors a profound cultural experience alongside stunning mountain backdrops.',
    image: './images/place1-1.png',
    gallery: [
      './images/place1-1.png',
      './images/place1-2.png',
      './images/place1-3.png',
    ],
    highlights: [
      'Seven towering bronze statues of Thai kings, each over 12 meters tall',
      'Beautiful manicured gardens with mountain backdrop',
      'Free admission — open daily from 6:00 AM to 8:00 PM',
      'Night illumination creates a spectacular atmosphere',
      'On-site museum with historical exhibits',
      'Ample parking and facilities for visitors',
    ],
    mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=12.5475,99.9472&travelmode=driving',
    coords: { lat: 12.5475, lng: 99.9472 },
  },
  {
    id: 'hua-hin-railway-station',
    name: 'Hua Hin Railway Station',
    tag: 'Heritage',
    preview: 'One of Thailand\'s most beautiful and historic railway stations, featuring iconic Victorian-Thai architecture.',
    description: 'Hua Hin Railway Station is one of the oldest and most beautiful railway stations in Thailand. Built during the reign of King Rama VI, the station showcases a unique blend of Victorian and traditional Thai architectural styles. Its distinctive red-and-cream colored wooden building with ornate peaked roofs has become an iconic landmark of Hua Hin. The Royal Waiting Room, originally located at Sanam Chan Palace, was relocated here and stands as a testament to the station\'s historical significance.',
    image: './images/place2-1.png',
    gallery: [
      './images/place2-1.png',
      './images/place2-2.png',
      './images/place2-3.png',
    ],
    highlights: [
      'Iconic Victorian-Thai architectural style with red and cream colors',
      'Historic Royal Waiting Room relocated from Sanam Chan Palace',
      'Still operational — trains depart daily to Bangkok and southern Thailand',
      'Perfect photo opportunity spot for heritage enthusiasts',
      'Located in the heart of Hua Hin town center',
      'Free entry and easily accessible on foot',
    ],
    mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=12.5693,99.9528&travelmode=driving',
    coords: { lat: 12.5693, lng: 99.9528 },
  },
  {
    id: 'mangrove-trail',
    name: 'Thung Sam Roi Yot Mangrove Trail',
    tag: 'Nature',
    preview: 'A serene elevated boardwalk winding through lush mangrove forests and pristine wetland ecosystems.',
    description: 'The Thung Sam Roi Yot Mangrove and Wetland Nature Trail offers an immersive experience into one of Thailand\'s most pristine coastal ecosystems. Located within the Sam Roi Yot National Park area, this elevated boardwalk winds through dense mangrove forests, passing over tranquil waterways teeming with marine life. The trail provides an educational journey through the vital mangrove ecosystem, which serves as a nursery for countless marine species and a natural buffer against coastal erosion.',
    image: './images/place3-1.png',
    gallery: [
      './images/place3-1.png',
      './images/place3-2.png',
      './images/place3-1.png',
    ],
    highlights: [
      'Elevated wooden boardwalk through pristine mangrove forest',
      'Rich biodiversity including birds, crabs, and mudskippers',
      'Part of the Sam Roi Yot National Park ecosystem',
      'Educational signage about mangrove ecology and conservation',
      'Peaceful and shaded trail — ideal for morning walks',
      'Photography paradise with unique reflections and textures',
    ],
    mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=12.2158,99.9639&travelmode=driving',
    coords: { lat: 12.2158, lng: 99.9639 },
  },
  {
    id: 'cicada-market',
    name: 'Cicada Market',
    tag: 'Market',
    preview: 'A vibrant weekend art and craft market featuring local artists, live music, and delicious street food.',
    description: 'Cicada Market is Hua Hin\'s premier art and lifestyle weekend market, offering a unique blend of creativity and culture. Open every Friday through Sunday evening, this charming open-air market features an eclectic mix of handmade art, original fashion, unique handicrafts, and a diverse food court serving both Thai and international cuisine. Live music performances and art exhibitions create an enchanting atmosphere that celebrates local artistic talent.',
    image: './images/place4-1.png',
    gallery: [
      './images/place4-1.png',
      './images/place4-2.png',
      './images/place4-1.png',
    ],
    highlights: [
      'Open Friday to Sunday, 4:00 PM to 11:00 PM',
      'Handmade art, fashion, and unique handicrafts by local artists',
      'Live music and performing arts every weekend',
      'Diverse food court with Thai and international cuisines',
      'Art gallery showcasing rotating exhibitions',
      'Family-friendly atmosphere with free admission',
    ],
    mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=12.5518,99.9644&travelmode=driving',
    coords: { lat: 12.5518, lng: 99.9644 },
  },
  {
    id: 'khao-kalok-beach',
    name: 'Khao Kalok Beach',
    tag: 'Beach',
    preview: 'A stunning hidden beach with dramatic rocky cliffs rising from turquoise waters — a true hidden gem.',
    description: 'Khao Kalok Beach is one of Prachuap Khiri Khan\'s most spectacular hidden gems. This pristine beach is defined by its dramatic rocky headland, Khao Kalok, which rises majestically from the turquoise waters of the Gulf of Thailand. Unlike the more crowded tourist beaches, Khao Kalok offers a tranquil escape with soft golden sand, crystal-clear waters, and breathtaking sunsets. The rocky formations create natural tide pools and offer excellent viewpoints for panoramic coastal photography.',
    image: './images/place5-1.png',
    gallery: [
      './images/place5-1.png',
      './images/place5-2.png',
      './images/place5-3.png',
    ],
    highlights: [
      'Dramatic rocky cliff formation rising from turquoise ocean',
      'Pristine and uncrowded — a true hidden gem',
      'Natural tide pools perfect for exploring marine life',
      'Breathtaking sunset views from the beach and hilltop',
      'Excellent spot for photography and peaceful relaxation',
      'Local seafood restaurants nearby serving fresh catches',
    ],
    mapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=12.4847,99.9642&travelmode=driving',
    coords: { lat: 12.4847, lng: 99.9642 },
  },
];
